version: "3.9"

services:
  db:
    container_name: tz_lyapanov_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TZLyapanovDB
    restart: always
    ports:
      - "54322:5432"
    volumes:
      - db-data:/var/lib/postgresql
      - ./src/main/db_init/init_db.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      tz-network:
        aliases:
          - db

  computer-hardware-store:
    build:
      context: .
      dockerfile: Dockerfile
    image: sashalyapanov/computer-hardware-store:latest
    container_name: computer-hardware-store
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TZLyapanovDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: docker
      PROJECT_PATH: /app
    depends_on:
      - db
    networks:
      tz-network:
        aliases:
          - computer-hardware-store

volumes:
  db-data:
    driver: local

networks:
  tz-network:
    driver: bridge